# Generated by Django 3.0.5 on 2020-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('autor', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
